#!/bin/bash
#\file    sync.sh
#\brief   Sync files from original (private use only).
#\author  Akihiko Yamaguchi, info@akihikoy.net
#\version 0.1
#\date    Jan.28, 2016
files=(  #This was generated by `git ls-files`
# .gitignore
CMakeLists.txt
Makefile
config/baymax.jpg
config/baymax.svg
config/teleop.yaml
# deprecated/m_flowc2_cmn.py
# deprecated/m_flowc2_gen.py
# deprecated/m_flowc_cmn.py
# deprecated/m_flowc_gen.py
# deprecated/m_test_plan.py
# deprecated/m_test_plan2.py
launch/bx_real.launch
launch/bx_sim1.launch
launch/bx_sim2.launch
launch/bx_sim_world.launch
launch/bx_state_validity_checker.launch
launch/lfd_teleop_joystick.launch
launch/lfd_teleop_joystick2.launch
launch/pr2_arm_navigation.launch
launch/pr2_mannequin_controllers.launch
launch/pr2_real_l.launch
launch/pr2_sim_l.launch
launch/pr2_state_validity_checker.launch
mainpage.dox
manifest.xml
models/obj/b100.yaml
models/obj/b101.yaml
models/obj/b102.yaml
models/obj/b32.yaml
models/obj/b50.pcd
models/obj/b50.yaml
models/obj/b51.yaml
models/obj/b52.pcd
models/obj/b52.yaml
models/obj/b53.pcd
models/obj/b53.yaml
models/obj/b54.yaml
models/obj/b55.yaml
models/obj/b56.yaml
models/obj/b57.yaml
models/obj/b58.yaml
models/obj/b59.yaml
models/obj/b60.yaml
models/obj/b61.yaml
models/obj/b62.yaml
models/obj/b63.yaml
models/obj/b64.yaml
models/obj/b65.yaml
models/obj/blank.yaml
models/robot/gripper.yaml
models/robot/gripper_bx.yaml
scripts/bx_joint_states.py
scripts/bx_set_gripw.py
scripts/core_tool.py
scripts/cui_tool.py
scripts/motions/__init__.py
scripts/motions/_default.py.a1
scripts/motions/_default.py.sample
scripts/motions/_exit.py.sample
scripts/motions/attr.py
scripts/motions/backtog.py
scripts/motions/bpmap.py
scripts/motions/calib2.py
scripts/motions/calib_x.py
scripts/motions/chx.py
scripts/motions/ctrl.py
scripts/motions/cv.py
scripts/motions/cvfilter1.py
scripts/motions/db.py
scripts/motions/errtoinit.py
scripts/motions/flow_dummy.py
scripts/motions/flow_sensor_depth.py
scripts/motions/flow_sensor_rgb.py
scripts/motions/flowc3_cmn.py
scripts/motions/flowc3_gen.py
scripts/motions/flowc3_spread.py
scripts/motions/flowc_tap.py
scripts/motions/grab.py
scripts/motions/grposeest.py
scripts/motions/help.py
scripts/motions/infer.py
scripts/motions/infer2.py
scripts/motions/infer_grab.py
scripts/motions/infer_grab2.py
scripts/motions/infer_obspose.py
scripts/motions/infer_pour.py
scripts/motions/infer_poursp.py
scripts/motions/infer_regrab.py
scripts/motions/infer_spread.py
scripts/motions/infer_traj.py
scripts/motions/init0.py
scripts/motions/init1.py
scripts/motions/initc.py
scripts/motions/initcmw.py
scripts/motions/initr0.py
scripts/motions/initx0.py
scripts/motions/keyctrl.py
scripts/motions/keytorso.py
scripts/motions/manmv.py
scripts/motions/move_to_x.py
scripts/motions/mtrack.py
scripts/motions/objgen.py
scripts/motions/objlocal.py
scripts/motions/objs.py
scripts/motions/objs2.py
scripts/motions/postgrab.py
scripts/motions/postpour.py
scripts/motions/pour.py
# scripts/motions/pour_dpl01.py
# scripts/motions/pour_dpl01log.py
# scripts/motions/pour_dplB01.py
# scripts/motions/pour_dplB01log.py
scripts/motions/pregrab.py
scripts/motions/prepour.py
scripts/motions/randx.py
scripts/motions/regrab.py
scripts/motions/release.py
scripts/motions/rtcalib_x.py
scripts/motions/rtposeest.py
scripts/motions/scene.py
scripts/motions/setbp.py
scripts/motions/setup_pour_scene.py
scripts/motions/spread.py
# scripts/motions/subpour.py
# scripts/motions/subpour_dplB01.py
# scripts/motions/subpour_dplB01log.py
scripts/motions/template.py
scripts/motions/test/__init__.py
scripts/motions/test/cnt.py
scripts/motions/test/col.py
scripts/motions/test/ctrl.py
scripts/motions/test/exp.py
scripts/motions/test/flowc.py
scripts/motions/test/flowc2.py
scripts/motions/test/flowmodel.py
scripts/motions/test/follow1.py
scripts/motions/test/hsm.py
scripts/motions/test/hsm2.py
scripts/motions/test/ik.py
scripts/motions/test/mvx.py
scripts/motions/test/mvx2.py
scripts/motions/test/opt1.py
scripts/motions/test/poseest.py
scripts/motions/test/poseest2.py
scripts/motions/test/poseest3.py
scripts/motions/test/poseestg.py
scripts/motions/test/psm.py
scripts/motions/test/psm2.py
scripts/motions/test/sm.py
scripts/motions/test/sm2.py
scripts/motions/test/smev.py
scripts/motions/test/test.py
scripts/motions/test/test2.py
scripts/motions/test/test3.py
scripts/motions/test/throw1.py
scripts/motions/test/viz.py
scripts/motions/test/yaml.py
scripts/motions/th.py
scripts/motions/tsim/__init__.py
scripts/motions/tsim/clean.py
scripts/motions/tsim/cma01.py
scripts/motions/tsim/config1.py
scripts/motions/tsim/core1.py
# scripts/motions/tsim/dpl00.py
# scripts/motions/tsim/dpl00log.py
# scripts/motions/tsim/dpl01.py
# scripts/motions/tsim/dpl01log.py
# scripts/motions/tsim/dpl02.py
# scripts/motions/tsim/dpl02log.py
# scripts/motions/tsim/dpl03.py
# scripts/motions/tsim/dpl03log.py
# scripts/motions/tsim/dpl03xanlyz.py
# scripts/motions/tsim/dpl04.py
# scripts/motions/tsim/dpl04log.py
# scripts/motions/tsim/dpl04p.py
# scripts/motions/tsim/dpl04plog.py
# scripts/motions/tsim/dpl04pxanlyz.py
# scripts/motions/tsim/dplB03.py
# scripts/motions/tsim/dplB03log.py
# scripts/motions/tsim/dplB05.py
# scripts/motions/tsim/dplB05log.py
# scripts/motions/tsim/dplB06.py
# scripts/motions/tsim/dplB06log.py
# scripts/motions/tsim/dplC03.py
# scripts/motions/tsim/dplC03log.py
# scripts/motions/tsim/dplC05.py
# scripts/motions/tsim/dplC05log.py
# scripts/motions/tsim/exp01.py
# scripts/motions/tsim/exp01a.py
# scripts/motions/tsim/exp01b.py
# scripts/motions/tsim/exp01c1.py
# scripts/motions/tsim/exp01c2.py
# scripts/motions/tsim/exp02.py
# scripts/motions/tsim/exp03.py
# scripts/motions/tsim/exp04.py
# scripts/motions/tsim/exp05.py
# scripts/motions/tsim/exp05b.py
# scripts/motions/tsim/exp06.py
scripts/motions/tsim/sm1.py
scripts/motions/tsim/test1.py
scripts/motions/tsimh1/__init__.py
scripts/motions/tsimh1/clean.py
scripts/motions/tsimh1/core1.py
scripts/motions/tsimh1/sm1.py
scripts/motions/tsimh1/spline1.py
scripts/motions/tsimh1/test1.py
scripts/motions/vibrate.py
scripts/motions/viz.py
scripts/robotiq_tcp_ctrl.py
src/CMA1.0.09-README.txt
src/__init__.py
# src/base/__init__.py
src/base/base_adv.py
src/base/base_chn.py
src/base/base_const.py
# src/base/base_dpl.py
# src/base/base_dpl2.py
# src/base/base_dpl3.py
src/base/base_exp.py
src/base/base_geom.py
src/base/base_ml.py
src/base/base_ml_dnn.py
src/base/base_ml_lwr.py
src/base/base_ml_lwr2.py
src/base/base_opt.py
src/base/base_opt2.py
src/base/base_sm.py
src/base/base_sys.py
src/base/base_traj.py
src/base/base_util.py
src/base/ros_base.py
src/base/ros_col.py
src/base/ros_col_mi.py
src/base/ros_rbt_bxtr.py
src/base/ros_rbt_pr2.py
src/base/ros_robot.py
src/base/ros_viz.py
src/cma.py
src/state_validity_checker_node.cpp
srv/GetAllowedCollisionMatrix.srv
srv/GetStateValidity.srv
srv/GetTrajectoryValidity.srv
srv/SetPlanningSceneDiff.srv
test/get_axis_angle.py
test/parameterizations.py
test/plot_traj.py
test/template.py
test/test_bx.py
# test/test_dpl2a.py
# test/test_dpl3a.py
test/test_lquad.py
test/test_lwr2a.py
test/test_tostdtype.py
test/toy1.py
urdf/baxter_sim.urdf
)
files2=""
for ((i=0; i<$((${#files[@]})); i++)) ; do
  files2="$files2 ${HOME}/ros_ws/lfd_trick/./${files[i]}"
done
rsync -azv -R -L ${files2} .
